### ISSUE TITLE
SSHMON data parsing issue

### ISSUE THREAD

**Issue by harinderbora** [tilln/jmeter-sshmon#10]
I’m doing a performance test using Jmeter and during the test I’m collecting the statistics for backend server performance , for this purpose I use SSHMON sample collector listener in my test plan https://github.com/tilln/jmeter-sshmon

I have also configured a CSV file path to check the response data received from the server Issue is that

Data is not recorded in the CSV file and also there is no graph shown for SSHMON listener
In the jemeter logs I can see the following error

```
 java.text.ParseException: Unparseable number: " [2J"
    at java.text.NumberFormat.parse(NumberFormat.java:434) ~[?:?]
    at nz.co.breakpoint.jmeter.vizualizers.sshmon.SSHMonSampler.generateSamples(SSHMonSampler.java:86) [jmeter-sshmon-1.2.jar:?]
    at kg.apc.jmeter.vizualizers.MonitoringResultsCollector.processConnectors(MonitoringResultsCollector.java:215) [jmeter-plugins-cmn-jmeter-0.6.jar:?]
    at kg.apc.jmeter.vizualizers.MonitoringResultsCollector.run(MonitoringResultsCollector.java:122) [jmeter-plugins-cmn-jmeter-0.6.jar:?]   at java.lang.Thread.run(Thread.java:832) [?:?]
```
  

To verify the SSH configuration and the received data format , I tried to make a SSH connection to the backend server using putty and with same user/pwd and command , I get the data in Putty , please see the attached screenshot

Do I have to change the powershell script to change the format of CPU data, if yes then in which format? I did not get any info on plugin page.

I would really appreciate if you could provide me some help for this case.

![image](https://user-images.githubusercontent.com/72332540/104135551-6ed8d700-5391-11eb-8e52-4778383b9c22.png)

**Comment by tilln** [comment]
Hi @harinderbora 

Can you please confirm what plugin version you are using?
Version 1.3 should fix this issue.
Please upgrade and report back.

Also answered on [Stackoverflow](https://stackoverflow.com/questions/65657773/issue-with-jmeter-sshmon-sample-collector-received-data-is-not-parsed-by-the-p/65658990#65658990).

**Comment by harinderbora** [comment]
Thanks a lot. It works now but it seems I had both 1.2 and 1.3 versions in  .lib\ext directory, I updated this already on 07.1.2020
so somehow if both versions are kept it does not take the latest version. but after removing version 1.2 , the graphs started working. but that's a minor thing.  I'm really very thankful for your help / hint. 
![sshmon2](https://user-images.githubusercontent.com/72332540/104149238-c862f500-53d5-11eb-9d7a-77f5ad18739e.PNG)

**Comment by harinderbora** [comment]
sorry may be I was too quick in my response I did more tests  and now I get another error with parsing, please see the exception below
```
2021-01-11 07:40:11,731 ERROR n.c.b.j.v.s.SSHMonSampler: Sample failure for administrator@ltagw01.nrhitest.local:4444 [powershell.exe -ExecutionPolicy Bypass -File "E:\perf\Memory.ps1"]
java.text.ParseException: Unparseable number: ""
	at java.text.NumberFormat.parse(NumberFormat.java:434) ~[?:?]
	at nz.co.breakpoint.jmeter.vizualizers.sshmon.SSHMonSampler.generateSamples(SSHMonSampler.java:71) [jmeter-sshmon-1.3.jar:?]
	at kg.apc.jmeter.vizualizers.MonitoringResultsCollector.processConnectors(MonitoringResultsCollector.java:215) [jmeter-plugins-cmn-jmeter-0.6.jar:?]
	at kg.apc.jmeter.vizualizers.MonitoringResultsCollector.run(MonitoringResultsCollector.java:122) [jmeter-plugins-cmn-jmeter-0.6.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by tilln** [comment]
Well, is it possible that this is the actual output of the remote command?
What's in the `Memory.ps1` script?

**Comment by harinderbora** [comment]
Memory.ps1 was fine , you can see the results in the image which is attached with my first comment. 
The issue was:
when I was running the sshd in debug mode to analyze the requests then it was taking the name of the performance counter in OS language ( German)  and when I used this as proper windows service, it started taking these counter name in English. So I just had to change the counter names from German language to English, then it started working again.. Thanks a lot for writing this plugin, it will help me a lot. I will close this issue now.

**Comment by tilln** [comment]
By the way, you can change the JMeter Property `jmeter.sshmon.locale` to match the OS language.

**Comment by harinderbora** [comment]
Thanks and sorry for the late response, should the value be en for english, is there a link for location codes ?

**Comment by tilln** [comment]
Yes, `en` would work.
Here's a link https://en.m.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by harinderbora** [comment]
Thanks I will try this out.
